# Generated by Django 2.1.2 on 2018-12-01 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='回答内容')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='回答时间')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='版块名称')),
                ('number', models.IntegerField(default=0, verbose_name='板块序号')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='test_pictures')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255, unique=True, verbose_name='问题标题')),
                ('question_text', models.TextField(verbose_name='详细描述')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('priority', models.IntegerField(default=1000, verbose_name='排序优先级')),
                ('good_num', models.IntegerField(default=0)),
                ('bad_num', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('question_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Category', verbose_name='板块名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Student', verbose_name='提问者'),
        ),
        migrations.AddField(
            model_name='answer',
            name='head_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Profile', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Student'),
        ),
    ]
