# Generated by Django 2.1.2 on 2018-11-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='回答内容')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='回答时间')),
            ],
        ),
        migrations.CreateModel(
            name='BadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='版块名称')),
            ],
        ),
        migrations.CreateModel(
            name='GoodNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255, unique=True, verbose_name='问题标题')),
                ('question_text', models.TextField(verbose_name='详细描述')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('priority', models.IntegerField(default=1000, verbose_name='排序优先级')),
                ('question_category', models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Category', verbose_name='板块名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Student', verbose_name='提问者'),
        ),
        migrations.AddField(
            model_name='goodnum',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Student'),
        ),
        migrations.AddField(
            model_name='badnum',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Student'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Student'),
        ),
    ]
