# Generated by Django 2.1.2 on 2018-11-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answer', '0002_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_and_answer.Category', verbose_name='板块名称'),
        ),
    ]
