# Generated by Django 2.1.2 on 2018-11-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_and_answer', '0003_auto_20181123_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='parent_answer_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_answer_text', to='question_and_answer.Answer'),
        ),
    ]
